BusinessCardVisualizer/Models/ErrorViewModel.cs
namespace BusinessCardVisualizer.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

BusinessCardVisualizer/Models/UserDataModel.cs
using System.ComponentModel.DataAnnotations;

namespace BusinessCardVisualizer.Models
{
	public class UserDataModel
	{
		[Required(ErrorMessage = "Name is required.")]
		[StringLength(50, MinimumLength = 4, ErrorMessage = "Name must be between 4 and 50 characters.")]
		public string Name { get; set; } = null!;

		[Required(ErrorMessage = "Position is required.")]
		[StringLength(20, MinimumLength = 2, ErrorMessage = "Position must be between 2 and 20 characters.")]
		public string Position { get; set; } = null!;

		[Required(ErrorMessage = "Phone is required.")]
		[StringLength(20, MinimumLength = 8, ErrorMessage = "Phone must be between 8 and 20 characters.")]
		public string Phone { get; set; } = null!;

		[StringLength(50, ErrorMessage = "Email must be no more than 50 characters.")]
		[EmailAddress(ErrorMessage = "Email must be in valid format.")]
		public string Email { get; set; }

		[Required(ErrorMessage = "Company is required.")]
		[StringLength(50, MinimumLength = 2, ErrorMessage = "Company must be between 2 and 50 characters.")]
		public string Company { get; set; } = null!;
	}
}

BusinessCardVisualizer/Controllers/BusinessCardController.cs
using BusinessCardVisualizer.Models;
using Microsoft.AspNetCore.Mvc;

namespace BusinessCardVisualizer.Controllers
{
	public class BusinessCardController : Controller
	{
		private UserDataModel defaultUser;

		public BusinessCardController()
		{
			defaultUser = new UserDataModel()
			{
				Name = "Ivan Petrov",
				Position = "WebDeveloper",
				Phone = "+39566776677",
				Email = "ivan.petrov@gmail.com",
				Company = "Samsung"
			};
		}
		public IActionResult Index()
		{
			return View(defaultUser);
		}

		[HttpPost]
		public IActionResult EditCard(UserDataModel model) 
		{
			if (!ModelState.IsValid)
			{
				return View("Index", model);
			}

			ViewBag.Title = "YourCard";

			return View("Index", model);
		}
	}
}

BusinessCardVisualizer/Controllers/HomeController.cs
using BusinessCardVisualizer.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BusinessCardVisualizer.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

BusinessCardVisualizer/Views/BusinessCard/Index.cshtml
@model UserDataModel
@{
	ViewData["Title"] = "Business Card";
}

<section class="businessCard">
	<p id="name">@Model.Name</p>
	<p id="position">@Model.Position</p>
	<p id="phone">@Model.Phone</p>
	@if (Model.Email != null)
	{
		<p id="email">@Model.Email</p>
	}
	<p id="company">@Model.Company</p>
</section>

<section class="yourData">
	<p>Enter your data here to see it in the business card:</p>
	<form asp-action="EditCard" method="post">
		<div class="form-group">
			<label asp-for="Name">Name</label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name"></span>
		</div>
		<div class="form-group">
			<label asp-for="Position">Position</label>
			<input asp-for="Position" class="form-control" />
			<span asp-validation-for="Position"></span>
		</div>
		<div class="form-group">
			<label asp-for="Phone">Phone Number</label>
			<input asp-for="Phone" class="form-control" />
			<span asp-validation-for="Phone"></span>
		</div>
		<div class="form-group">
			<label asp-for="Email">Email</label>
			<input asp-for="Email" class="form-control" />
			<span asp-validation-for="Email"></span>
		</div>
		<div class="form-group">
			<label asp-for="Company">Company</label>
			<input asp-for="Company" class="form-control" />
			<span asp-validation-for="Company"></span>
		</div>
		<button type="submit" class="btn btn-primary">Put my data</button>
	</form>
</section>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

BusinessCardVisualizer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is my sample ASP.NET Core app for visualizing a business card.</a>.</p>
</div>

BusinessCardVisualizer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BusinessCardVisualizer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BusinessCardVisualizer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BusinessCardVisualizer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BusinessCard" asp-action="Index">Business Card</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BusinessCardVisualizer
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>